/** Independent scopes fit the existing per-reading requirement inventory.
 * Transport batches must preserve this inventory rather than narrow its scope. */
export const LEGAL_INTERPRETATION_REQUIREMENT_LIMIT = 20;
export const LEGAL_DISCOVERED_REQUIREMENT_LIMIT = 3;
export const LEGAL_EXPANDED_REQUIREMENT_LIMIT = LEGAL_INTERPRETATION_REQUIREMENT_LIMIT + LEGAL_DISCOVERED_REQUIREMENT_LIMIT;
export const LEGAL_INTERPRETATION_FORMULATION_LIMIT = 20;
export const LEGAL_REPAIR_FORMULATION_LIMIT = 4;
export const LEGAL_TOTAL_FORMULATION_LIMIT = LEGAL_INTERPRETATION_FORMULATION_LIMIT + LEGAL_REPAIR_FORMULATION_LIMIT;
