"use client";

import { Select } from "../_components/Select";
import { RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { PlatformLocale } from "../../lib/platform/routing";
type Locale=PlatformLocale; type Ticket={id:string;subject:string;category:string;severity:string;status:"open"|"waiting_user"|"resolved"}; type Message={id:string;authorType:"requester"|"staff";body:string};
const copy={ru:{title:"Обращения в поддержку",refresh:"Обновить",reply:"Ответить",send:"Отправить",empty:"Обращений нет",status:"Статус",queue:"Очередь обращений",secure:"Защищённая рабочая зона",fresh:"Недавняя 2FA",message:"Сообщение",requester:"Пользователь",staff:"Поддержка",open:"Открыто",waiting_user:"Ожидается ответ пользователя",resolved:"Решено",low:"Низкий",normal:"Обычный",high:"Высокий",critical:"Критический",updated:"Список обращений обновлён",details:"Детали обращения загружены"},uz:{title:"Qo‘llab-quvvatlash murojaatlari",refresh:"Yangilash",reply:"Javob berish",send:"Yuborish",empty:"Murojaatlar yo‘q",status:"Holat",queue:"Murojaatlar navbati",secure:"Himoyalangan ish maydoni",fresh:"Yaqindagi 2FA",message:"Xabar",requester:"Foydalanuvchi",staff:"Qo‘llab-quvvatlash",open:"Ochiq",waiting_user:"Foydalanuvchi javobi kutilmoqda",resolved:"Hal qilindi",low:"Past",normal:"Oddiy",high:"Yuqori",critical:"Muhim",updated:"Murojaatlar ro‘yxati yangilandi",details:"Murojaat tafsilotlari yuklandi"},en:{title:"Support requests",refresh:"Refresh",reply:"Reply",send:"Send",empty:"No support requests",status:"Status",queue:"Support queue",secure:"Secure workspace",fresh:"Recent 2FA",message:"Message",requester:"User",staff:"Support",open:"Open",waiting_user:"Waiting for user",resolved:"Resolved",low:"Low",normal:"Normal",high:"High",critical:"Critical",updated:"Support request list refreshed",details:"Support request details loaded"}} as const;
async function json<T>(response:Response){const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body;}
export function SupportInbox({locale,staffName}:{locale:Locale;staffName:string}){
 const t=copy[locale];const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [status,setStatus]=useState<Ticket["status"]>("open");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{setTickets((await json<{tickets:Ticket[]}>(await fetch("/api/platform/admin/support-tickets",{cache:"no-store"}))).tickets);setError("");}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function open(ticket:Ticket){setBusy(true);try{const data=await json<{ticket:Ticket;messages:Message[]}>(await fetch(`/api/platform/admin/support-tickets/${ticket.id}`,{cache:"no-store"}));setSelected(data.ticket);setMessages(data.messages);setStatus(data.ticket.status);setError("");}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(!selected||!text.trim())return;setBusy(true);try{await json(await fetch(`/api/platform/admin/support-tickets/${selected.id}`,{method:"POST",headers:{"content-type":"application/json","x-juro-csrf":"1"},body:JSON.stringify({body:text.trim(),status})}));setText("");await open(selected);await load();}catch(e){setError(e instanceof Error?e.message:"ERROR");}finally{setBusy(false);}}
 return <div className="staff-console" aria-busy={busy}><header className="staff-topbar"><div className="staff-brand"><ShieldCheck aria-hidden="true"/><span><b>JURO</b><small>{t.secure}</small></span></div><div className="staff-session"><span>{t.fresh}</span><b>{staffName}</b></div></header><main className="staff-main"><section className="staff-heading"><div><p>{t.queue}</p><h1>{t.title}</h1></div><button type="button" onClick={()=>void load()} disabled={busy}><RefreshCw aria-hidden="true"/>{t.refresh}</button></section><p className="sr-only" aria-live="polite">{busy?"":selected?t.details:t.updated}</p>{error&&<p className="staff-error" role="alert">{error}</p>}<section className="staff-queue" aria-label={t.queue}>{tickets.length?tickets.map(ticket=><article className="staff-table-row" key={ticket.id}><div className="staff-source"><span>{t[ticket.severity as "low"|"normal"|"high"|"critical"]??ticket.severity}</span><b>{ticket.subject}</b><small>{ticket.category}</small></div><div className={`staff-status status-${ticket.status}`}>{t[ticket.status]}</div><div className="staff-row-actions"><button type="button" onClick={()=>void open(ticket)} disabled={busy} aria-label={`${t.reply}: ${ticket.subject}`}>{t.reply}</button></div></article>):<p className="staff-empty">{t.empty}</p>}</section>{selected&&<form className="staff-decision" onSubmit={event=>void submit(event)} aria-labelledby="support-ticket-subject"><h2 id="support-ticket-subject">{selected.subject}</h2><div className="staff-support-messages">{messages.map(message=><article key={message.id}><b>{message.authorType==="staff"?t.staff:t.requester}</b><p>{message.body}</p></article>)}</div><label>{t.message}<textarea required value={text} onChange={event=>setText(event.target.value)} aria-label={t.message}/></label><label>{t.status}<Select value={status} onChange={event=>setStatus(event.target.value as Ticket["status"])}><option value="open">{t.open}</option><option value="waiting_user">{t.waiting_user}</option><option value="resolved">{t.resolved}</option></Select></label><button className="staff-approve" disabled={busy||!text.trim()}><Send aria-hidden="true"/>{t.send}</button></form>}</main></div>;
}
