import type { PlatformLocale } from "../../lib/platform/routing";

export type AccountView = "profile" | "settings" | "security" | "privacy";

export const accountSettingsCopy = {
  en: {
    account: "Your account", personal: "Personal workspace", navigation: "Account sections",
    profile: { title: "Profile", short: "Your details", description: "Keep your personal details up to date." },
    settings: { title: "Settings", short: "Make JURO yours", description: "Choose how JURO fits into your working day." },
    security: { title: "Security", short: "Sign-in & devices", description: "Manage how you sign in and where your account is open." },
    privacy: { title: "Privacy", short: "Your data & choices", description: "Decide what JURO remembers and how your data is used." },
    details: "Personal details", detailsDescription: "Your name and contact information for your JURO account.",
    preferences: "Language & region", preferencesDescription: "Set the language you read and the time zone you work in.",
    email: "Sign-in email",
    saved: "No unsaved changes", unsaved: "You have unsaved changes", saving: "Saving…", discard: "Discard changes",
    professional: "Professional profile", professionalDescription: "Manage the expertise and information clients see on your lawyer profile.",
    workspaceDescription: "Keep your organisation’s matters and documents in a separate workspace.",
    historyDescription: "Review the policies and permissions you have accepted.",
    deleteDescription: "Review your options before requesting account deletion.",
    memoryAddDescription: "Add a fact or preference you want JURO to remember.",
    signIn: "Email & sign-in", devices: "Your devices", devicesDescription: "Review your JURO sign-ins. Sign out any device you no longer use.",
    allDevices: "Show all devices", fewerDevices: "Show fewer devices", emailCode: "Email code", password: "Password", developmentSignIn: "Development sign-in",
    optional: "Optional", retry: "Try again",
  },
  ru: {
    account: "Ваш аккаунт", personal: "Личное пространство", navigation: "Разделы аккаунта",
    profile: { title: "Профиль", short: "Личные данные", description: "Поддерживайте ваши личные данные в актуальном состоянии." },
    settings: { title: "Настройки", short: "JURO под вас", description: "Настройте JURO под свой рабочий день." },
    security: { title: "Безопасность", short: "Вход и устройства", description: "Управляйте входом в аккаунт и подключёнными устройствами." },
    privacy: { title: "Приватность", short: "Данные и разрешения", description: "Решайте, что JURO запоминает и как используются ваши данные." },
    details: "Личные данные", detailsDescription: "Имя и контактная информация вашего аккаунта JURO.",
    preferences: "Язык и регион", preferencesDescription: "Выберите язык интерфейса и свой часовой пояс.",
    email: "Email для входа",
    saved: "Нет несохранённых изменений", unsaved: "Есть несохранённые изменения", saving: "Сохраняем…", discard: "Отменить изменения",
    professional: "Профессиональный профиль", professionalDescription: "Настройте информацию об опыте и услугах, которую видят клиенты.",
    workspaceDescription: "Отдельное пространство для дел и документов вашей организации.",
    historyDescription: "Просмотрите принятые условия и предоставленные разрешения.",
    deleteDescription: "Ознакомьтесь с вариантами перед запросом на удаление аккаунта.",
    memoryAddDescription: "Добавьте факт или предпочтение, которые JURO должен запомнить.",
    signIn: "Email и вход", devices: "Ваши устройства", devicesDescription: "Просмотрите входы в JURO. Завершите сессии на устройствах, которыми больше не пользуетесь.",
    allDevices: "Все устройства", fewerDevices: "Свернуть список", emailCode: "Код из письма", password: "Пароль", developmentSignIn: "Вход для разработки",
    optional: "Необязательно", retry: "Повторить",
  },
  uz: {
    account: "Hisobingiz", personal: "Shaxsiy ish maydoni", navigation: "Hisob bo‘limlari",
    profile: { title: "Profil", short: "Shaxsiy ma’lumotlar", description: "Shaxsiy ma’lumotlaringizni yangilab turing." },
    settings: { title: "Sozlamalar", short: "JURO sizga mos", description: "JURO’ni ish kuningizga moslashtiring." },
    security: { title: "Xavfsizlik", short: "Kirish va qurilmalar", description: "Hisobga kirish va faol qurilmalarni boshqaring." },
    privacy: { title: "Maxfiylik", short: "Ma’lumot va ruxsatlar", description: "JURO nimani eslab qolishi va ma’lumotlardan qanday foydalanishini belgilang." },
    details: "Shaxsiy ma’lumotlar", detailsDescription: "JURO hisobingizdagi ism va aloqa ma’lumotlari.",
    preferences: "Til va hudud", preferencesDescription: "Interfeys tili va ish vaqt mintaqasini tanlang.",
    email: "Kirish emaili",
    saved: "Saqlanmagan o‘zgarishlar yo‘q", unsaved: "Saqlanmagan o‘zgarishlar bor", saving: "Saqlanmoqda…", discard: "O‘zgarishlarni bekor qilish",
    professional: "Professional profil", professionalDescription: "Mijozlar ko‘radigan tajriba va xizmatlar haqidagi ma’lumotlarni boshqaring.",
    workspaceDescription: "Tashkilotingiz ishlari va hujjatlari uchun alohida ish maydoni.",
    historyDescription: "Qabul qilingan shartlar va berilgan ruxsatlarni ko‘ring.",
    deleteDescription: "Hisobni o‘chirishni so‘rashdan oldin variantlarni ko‘rib chiqing.",
    memoryAddDescription: "JURO eslab qolishi kerak bo‘lgan fakt yoki afzallikni qo‘shing.",
    signIn: "Email va kirish", devices: "Qurilmalaringiz", devicesDescription: "JURO’ga kirishlarni ko‘ring. Ishlatmayotgan qurilmalardagi seanslarni yakunlang.",
    allDevices: "Barcha qurilmalar", fewerDevices: "Kamroq ko‘rsatish", emailCode: "Email kodi", password: "Parol", developmentSignIn: "Ishlab chiqish uchun kirish",
    optional: "Ixtiyoriy", retry: "Qayta urinish",
  },
} satisfies Record<PlatformLocale, object>;
