'use client';
import {useEffect,useState,type FormEvent} from 'react';
import type {PlatformLocale} from '../../lib/platform/routing';
export function ProfessionalCredentials({locale,profileId}:{locale:PlatformLocale;profileId?:string}){
 const [data,setData]=useState<any>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[type,setType]=useState('lawyer');
 const text=(ru:string,uz:string,en:string)=>locale==='uz'?uz:locale==='en'?en:ru;
 const load=async()=>{const r=await fetch('/api/platform/lawyer-profile/credentials',{cache:'no-store'});if(r.ok){const d=await r.json();setData(d);setType(d.details?.professional_type??d.defaultType??'lawyer');}};
 useEffect(()=>{void load();},[profileId]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setNotice('');const form=new FormData(event.currentTarget);try{const upload=form.has('file');const r=await fetch('/api/platform/lawyer-profile/credentials',{method:'POST',headers:upload?{}:{'content-type':'application/json'},body:upload?form:JSON.stringify({professionalType:type,organizationName:String(form.get('organizationName')??'')||null,registrationNumber:String(form.get('registrationNumber')??'')||null,licenseNumber:String(form.get('licenseNumber')??'')||null,representatives:String(form.get('representatives')??'').split('\n').filter(v=>v.trim()).map(v=>{const [name,position='',email='']=v.split('|');return {name:name.trim(),position:position.trim(),email:email.trim()};})})});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(text('Сохранено. Существенные изменения требуют повторной проверки JURO.','Saqlandi. Muhim o‘zgarishlar JURO tekshiruvini talab qiladi.','Saved. Material changes require JURO review.'));await load();}catch(e){setNotice(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}};
 if(!data)return null;const d=data.details;
 return <section><h2>{text('Тип профиля и подтверждающие документы','Profil turi va tasdiqlovchi hujjatlar','Profile type and verification documents')}</h2><p>{text('Документы доступны только уполномоченному администратору JURO. Они не публикуются в каталоге.','Hujjatlarni faqat JURO administratori ko‘radi. Ular katalogda e’lon qilinmaydi.','Documents are available only to the JURO administrator and are never public.')}</p><form onSubmit={submit}><label>{text('Тип участника','Ishtirokchi turi','Professional type')}<select value={type} onChange={e=>setType(e.target.value)}>{[['lawyer','Юрист','Yurist','Lawyer'],['advocate','Адвокат','Advokat','Advocate'],['firm','Юридическая фирма','Yuridik firma','Legal firm'],['other','Другой специалист','Boshqa mutaxassis','Other professional']].map(([v,ru,uz,en])=><option key={v} value={v}>{text(ru,uz,en)}</option>)}</select></label>{type==='firm'&&<><label>{text('Название организации','Tashkilot nomi','Organization name')}<input name="organizationName" defaultValue={d?.organization_name??''} required maxLength={300}/></label><label>{text('Регистрационный номер','Ro‘yxatga olish raqami','Registration number')}<input name="registrationNumber" defaultValue={d?.registration_number??''} required maxLength={100}/></label><label>{text('Представители: имя | должность | email, по одному на строку','Vakillar: ism | lavozim | email, har biri yangi qatorda','Representatives: name | position | email, one per line')}<textarea name="representatives" defaultValue={(d?.representatives??[]).map((v:any)=>`${v.name} | ${v.position} | ${v.email}`).join('\n')}/></label></>}{type==='advocate'&&<label>{text('Номер лицензии адвоката','Advokat litsenziyasi raqami','Advocate license number')}<input name="licenseNumber" defaultValue={d?.license_number??''} required maxLength={100}/></label>}<button disabled={busy}>{text('Сохранить сведения','Ma’lumotlarni saqlash','Save details')}</button></form><form onSubmit={submit}><label>{text('Вид документа','Hujjat turi','Document kind')}<select name="kind"><option value="education">{text('Образование','Ta’lim','Education')}</option>{type==='advocate'&&<option value="license">{text('Лицензия','Litsenziya','License')}</option>}{type==='firm'&&<><option value="registration">{text('Регистрация организации','Tashkilot ro‘yxati','Company registration')}</option><option value="authority">{text('Полномочия представителя','Vakil vakolati','Representative authority')}</option></>}<option value="other">{text('Дополнительные сведения','Qo‘shimcha ma’lumot','Other')}</option></select></label><input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/><p>PDF, JPEG, PNG · ≤ 10 MB</p><button disabled={busy}>{text('Загрузить документ','Hujjat yuklash','Upload document')}</button></form><ul>{data.documents.map((v:any)=><li key={v.id}>{v.file_name} · {v.kind}</li>)}</ul>{notice&&<p role="status">{notice}</p>}</section>;
}
