import type { LandingContent } from "./types";

export const uz: LandingContent = {
  meta: {
    title: "JURO — AI va jonli yurist bitta himoyalangan makonda",
    description: "JURO — AI-yordam, hujjatlar va yuristlar bitta xizmatda.",
  },
  nav: { capabilities: "Imkoniyatlar", how: "Qanday ishlaydi", pricing: "Tariflar", security: "Xavfsizlik", faq: "FAQ", login: "Kirish", start: "Bepul boshlash", menuOpen: "Menyuni ochish", menuClose: "Menyuni yopish", skip: "Asosiy mazmunga o‘tish" },
  hero: {
    eyebrow: "JURO — cho‘ntagingizdagi yurist",
    subtitle: "Vaziyatni yozing — AI faktlarni aniqlashtiradi, reja yoki hujjat tayyorlaydi va zarur bo‘lsa yig‘ilgan kontekstni jonli yuristga topshiradi.",
    chips: ["AI + jonli yurist", "Rus va o‘zbek tillari", "Ma’lumotlar himoyada"],
    primary: "Vaziyatimni bepul tahlil qilish",
    secondary: "JURO demosini ko‘rish",
    jurobekAlt: "Jurobek — JURO raqamli yuridik yordamchisi",
  },
  demo: {
    label: "JURO AI demo",
    title: "Nima bo‘ldi?",
    description: "Shaxsiy ma’lumotlarsiz vaziyatni yozing. Demo qanday faktlarni aniqlashtirish va qaysi keyingi qadamni taklif qilish mumkinligini ko‘rsatadi.",
    placeholder: "Masalan: ish beruvchi ikki oydan beri maoshni kechiktirmoqda…",
    send: "Savolni yuborish",
    analyzing: "JURO vaziyatni tahlil qilmoqda",
    error: "Demo-javob tayyorlanmadi. Yana urinib ko‘ring.",
    continueTitle: "JURO makoningizda bepul davom eting",
    continueBody: "Ro‘yxatdan keyin tasdiqlangan faktlarni saqlash, hujjatlar qo‘shish va shu bosqichdan davom etish mumkin.",
    consent: "Matn faqat alohida tasdiqdan keyin akkauntimda saqlanishini tushunaman.",
    continueCta: "Vaziyatni saqlash va davom etish",
    disclaimer: "Demo yakuniy huquqiy xulosa bermaydi va majburiy professional yordamni almashtirmaydi.",
  },
  audience: {
    eyebrow: "Kim uchun",
    title: "Ish ssenariyingizni tanlang",
    body: "Avval rolingizni tanlang. Biznes uchun uchta alohida variant ochiladi — ekranda bir vaqtning o‘zida uchtadan ortiq teng tanlov bo‘lmaydi.",
    top: [
      { id: "self", title: "O‘zim uchun", body: "Shaxsiy savollar, hujjatlar va yuridik jargonsiz tushunarli reja.", scenarios: ["oila va mehnat", "qarz va tilxat", "uy-joy va xarid"], cta: "Shaxsiy masalani hal qilish" },
      { id: "business", title: "Biznes uchun", body: "Shartnomalar, talabnomalar, jamoa, muddatlar va korporativ hujjatlar.", scenarios: ["startap", "kichik biznes", "yuridik jarayonlar"], cta: "Biznes turini tanlash" },
      { id: "lawyer", title: "Men yuristman", body: "Tadqiqot, shablonlar, versiyalar va takroriy ishlarni avtomatlashtirish.", scenarios: ["hujjat tayyorlash", "birgalikda kelishish", "o‘zgarishlar tarixi"], cta: "Yuridik rutinani avtomatlashtirish" },
    ],
    business: [
      { id: "startup", title: "Startap", body: "NDA, founders agreements, IP hamda investitsiya va jamoa hujjatlari.", scenarios: ["jamoa", "investorlar", "intellektual mulk"], cta: "Startap hujjatlarini tayyorlash" },
      { id: "small", title: "Kichik biznes", body: "Shartnomalar, qarzdorlik, ijara, xodimlar, yetkazib beruvchilar va mijozlar.", scenarios: ["shartnomalar", "talabnomalar", "kadr hujjatlari"], cta: "Shartnomalarni tartibga keltirish" },
      { id: "enterprise", title: "O‘rta va yirik biznes", body: "Rollar, kelishuv, versiyalar, muddatlar va boshqariladigan yuridik hisobot.", scenarios: ["kirish huquqlari", "jarayonlar", "xavflarni nazorat qilish"], cta: "Yuridik jarayonlarni sozlash" },
    ],
  },
  capabilities: {
    eyebrow: "Imkoniyatlar",
    title: "Olti vosita — bitta yuridik jarayon",
    body: "Har bir natija ish bilan bog‘liq qoladi: hujjat, reja yoki mutaxassisga o‘tishda faktlarni takrorlash shart emas.",
    items: [
      { title: "AI-yurist", body: "Vaziyatni yozing va xulosadan foydalanishdan oldin faktlarni tasdiqlang.", result: "Tuzilgan tahlil va aniqlashtiruvchi savollarni oling.", cta: "Vaziyatni tahlil qilish", path: "/ai-chat", accountRequired: true },
      { title: "Hujjatlarni tekshirish", body: "Hujjatni yuklang va tegishli qismlar yonida izohlarni oching.", result: "Qisqa mazmun, bo‘shliqlar va ishonch darajali xavflarni oling.", cta: "Shartnomani tekshirish", path: "/document-review", accountRequired: true },
      { title: "Hujjat yaratish", body: "Savollarga javob bering, previewni tekshiring va tahrirlanadigan loyihani saqlang.", result: "Shablon versiyasi ko‘rsatilgan DOCX yoki PDF oling.", cta: "Hujjat yaratish", path: "/document-builder", accountRequired: true },
      { title: "Harakatlar rejasi", body: "Qadamlar, mas’ullar, hujjatlar va muddatlarni aniq ishga bog‘lang.", result: "Jarayon va keyingi harakatni ko‘ring.", cta: "Reja tuzish", path: "/action-plan", accountRequired: true },
      { title: "Jonli yurist", body: "Materiallarni tanlang va uzatiladigan kirish hajmini tasdiqlang.", result: "Mutaxassis bo‘sh chat emas, tayyor kontekstni oladi.", cta: "Yuristni jalb qilish", path: "/consultations", accountRequired: true },
      { title: "Hamkorlik", body: "Tomon, vakil yoki yuristni alohida huquqlar bilan qo‘shing.", result: "Izohlar, takliflar va versiyalar tarixda saqlanadi.", cta: "Jamoani taklif qilish", path: "/team", accountRequired: true },
    ],
  },
  how: { eyebrow: "Qanday ishlaydi", title: "Savoldan tekshiriladigan harakatgacha", body: "JURO tasdiqlangan faktlarni taxminlardan ajratib, bosqichma-bosqich olib boradi.", steps: ["Vaziyatni yozing", "Faktlarni aniqlashtiring", "Manbalarni tekshiring", "Xavflarni tushuning", "Reja tuzing", "Hujjat tayyorlang", "Zarur bo‘lsa yuristni jalb qiling"], note: "Har bir keyingi bosqich tasdiqlangan ma’lumotlardan foydalanadi. Jonli yuristga topshirish faqat foydalanuvchi roziligi bilan bajariladi." },
  comparison: {
    eyebrow: "JURO ≠ CHATBOT",
    title: "Shunchaki javob emas. Boshqariladigan yuridik jarayon",
    body: "JUROni har qanday AI tizimi bilan emas, oddiy bir martalik chat tajribasi bilan taqqoslaymiz.",
    ordinaryTitle: "Oddiy bir martalik AI-chat",
    juroTitle: "JURO",
    ordinary: ["Alohida javob", "Ish holati yo‘q", "Kontekstni ko‘pincha takrorlash kerak", "Hujjatlar ishga bog‘lanmagan", "Muddat va jarayon yo‘q", "Mutaxassisga boshqariladigan topshirish yo‘q", "Tarix xabarlar to‘plami bo‘lib qoladi"],
    juro: ["Yagona ish va xronologiya", "Tasdiqlangan faktlar", "Hujjatlar va dalillar", "Muddat va xavflar", "Reja va jarayon", "Hamkorlik", "Tanlangan kontekst bilan jonli yuristga topshirish"],
  },
  handoff: {
    eyebrow: "AI + jonli yurist",
    title: "Mutaxassis ishni noldan boshlamaydi",
    body: "AI vaziyatni tezroq tayyorlaydi. Jonli mutaxassis yig‘ilgan faktlar, hujjatlar va savollar bilan ishlashni boshlaydi.",
    stages: ["AI-tahlil", "Tasdiqlangan faktlar", "Hujjatlar va reja", "Jonli mutaxassis kontekstni oladi"],
    note: "Maslahatning mavjudligi va narxi tarif hamda tanlangan formatga bog‘liq.",
    cta: "Maslahatlarni ko‘rish",
  },
  security: {
    eyebrow: "Ishonch va xavfsizlik",
    title: "Mutlaq va’dalar emas, aniq mexanizmlar",
    body: "Maxfiy obyektlarga kirish sessiya, rol va ishtirokchi huquqlari bilan cheklanadi.",
    items: [
      { title: "Yopiq ish makoni", body: "Shaxsiy ishlar va hujjatlar ommaviy sahifa hamda sitemapga kirmaydi." },
      { title: "Rollar va huquqlar", body: "Ko‘rish, izoh, o‘zgartirish va yuklash alohida belgilanadi." },
      { title: "Maxfiy fayllar", body: "Fayllarda doimiy ommaviy URL yo‘q; havolalar muddat bilan cheklanadi." },
      { title: "Harakatlar tarixi", body: "Izoh, taklif, versiya va kirishlar xronologiyada qayd etiladi." },
    ],
    serverLine: "Kirish huquqlari serverda tekshiriladi.",
  },
  pricing: {
    eyebrow: "Tariflar",
    title: "Tushunarli boshlanish va to‘lovdan oldingi shartlar",
    body: "Jonli mutaxassis xizmati alohida ko‘rsatiladi va to‘g‘ridan-to‘g‘ri tarifga kiritilgan deb hisoblanmaydi.",
    plans: [
      { id: "personal", title: "Shaxsiy makon", items: ["Shaxsiy vaziyat uchun AI-tahlil", "Ishlar, rejalar va hujjatlar", "Bepul boshlanishda birinchi hujjat"], cta: "O‘zim uchun boshlash" },
      { id: "business", title: "Biznes makoni", badge: "Ommabop", items: ["Shartnoma va talabnomalar", "Rollar va hamkorlik", "Versiyalar tarixi va muddatlar"], cta: "Kompaniya makonini yaratish" },
      { id: "legal", title: "Yuridik jamoa", items: ["Kutubxona va muharrir", "Kelishuv va audit", "Jamoa rollari"], note: "Yuristning individual xizmatlari alohida hisoblanadi.", cta: "Yuridik bo‘lim uchun muhokama qilish" },
    ],
  },
  knowledge: {
    eyebrow: "Bilimlar bazasi",
    title: "Qaror qabul qilishdan oldin huquqni tushuning",
    body: "Amaliy materiallar ish ssenariysidan oldin fakt va hujjatlarni tayyorlashga yordam beradi.",
    cta: "Bilimlar bazasini ochish",
    items: [
      { slug: "contract-review-preparation", title: "Shartnomani tekshirishga qanday tayyorlanish", description: "Qaysi versiyalar, ilovalar, yozishmalar va savollarni oldindan yig‘ish kerak." },
      { slug: "facts-for-action-plan", title: "Harakatlar rejasi uchun qanday faktlar kerak", description: "Tasdiqlangan holatlarni taxminlardan qanday ajratish mumkin." },
      { slug: "when-lawyer-review-is-needed", title: "Hujjatni qachon jonli yurist tekshirishi kerak", description: "Murakkab, shoshilinch yoki yuqori xavfli hujjat belgilari." },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Ko‘p beriladigan savollar",
    body: "Imkoniyatlar, xavflar, ma’lumotlar va mutaxassisga o‘tish haqida to‘liq javoblar.",
    items: [
      { question: "JURO nima?", answer: "JURO — yuridik vaziyatni tuzish, faktlarni aniqlash, xulosani manba bilan bog‘lash, harakatlar rejasi yoki hujjat tayyorlash va zarur bo‘lsa tanlangan kontekstni jonli yuristga topshirishga yordam beradigan LegalTech platforma." },
      { question: "JURO jonli yuristni almashtiradimi?", answer: "Yo‘q. AI ishni tayyorlash va tezlashtirishga yordam beradi, lekin xato qilishi mumkin va majburiy professional, notarial yoki davlat tartibini almashtirmaydi. Murakkab, shoshilinch va yuqori xavfli savollarni malakali mutaxassisga topshirish tavsiya etiladi." },
      { question: "JURO ChatGPTdan nimasi bilan farq qiladi?", answer: "JURO ish atrofida boshqariladigan yuridik jarayon yaratadi: tasdiqlangan faktlar, hujjatlar, muddatlar, versiyalar, reja va mutaxassisga topshiriladigan kontekstni saqlaydi. Bu boshqa AI tizimlari texnik jihatdan kontekstni saqlay olmaydi degani emas." },
      { question: "Javoblar qaysi qonunchilikka asoslanadi?", answer: "Qo‘llaniladigan huquq faktlar va tanlangan yurisdiksiya bo‘yicha belgilanadi. O‘zbekiston bo‘yicha JURO dolzarb rasmiy manbalarga, jumladan LexUZga tayanishi va foydalanuvchi hujjati, huquqiy manba hamda AI xulosasini alohida ko‘rsatishi kerak." },
      { question: "JURO manbalarni ko‘rsatadimi?", answer: "JUROning maqsadli jarayoni huquqiy asosni tegishli xulosa yonida ko‘rsatadi. Rasmiy manba mavjud yoki tasdiqlangan bo‘lmasa, tizim uni soxta havola yoki ishonchli bayonot bilan almashtirmasligi kerak." },
      { question: "Shartnomani yuklash mumkinmi?", answer: "Ha, himoyalangan akkauntda va qo‘llab-quvvatlanadigan formatda. Ommaviy landing haqiqiy fayllarni qabul qilmaydi, chunki hujjatlar avtorizatsiya, rozilik, himoyalangan saqlash va o‘chirish siyosatisiz qayta ishlanmasligi kerak." },
      { question: "Hujjatning ikki versiyasini solishtirish mumkinmi?", answer: "Ha. Solishtirish vositasi mazmuniy o‘zgarish, «oldin va keyin» tahriri, xavf o‘zgarishi, ehtimoliy oqibat va tavsiyani ko‘rsatishi hamda ikkala versiyani ish kontekstida saqlashi kerak." },
      { question: "Hujjat yaratish mumkinmi?", answer: "Ha. Konstruktor ma’lumotlarni bosqichma-bosqich yig‘adi, tahrirlanadigan loyiha yaratadi va tomonlar, sanalar, summalar hamda muhim shartlarni tekshirish imkonini beradi. Yuridik kuch mazmun, shakl, imzo va majburiy tartiblarga bog‘liq." },
      { question: "Rus va o‘zbek tillari qo‘llanadimi?", answer: "Ha. Ommaviy sayt va asosiy mahsulot ssenariylari rus va o‘zbek tillarida ko‘zda tutilgan. Tilni almashtirish joriy sahifani saqlashi va tanlangan ssenariyni zaruratsiz bekor qilmasligi kerak." },
      { question: "Ma’lumotlarim qanday himoyalanadi?", answer: "Yopiq ishlar va hujjatlar ommaviy sahifa yoki sitemapga kirmaydi; kirish sessiya, rol va ishtirokchi huquqlariga bog‘liq. Saqlash, o‘chirish, AI-provayderlar va tasdiqlangan texnik choralar Trust Centerda e’lon qilinadi." },
      { question: "Hujjatlar modelni o‘qitishda ishlatiladimi?", answer: "JURO tasdiqlangan production konfiguratsiyasi va provayder shartlarisiz umumiy va’da bermaydi. Har bir AI-provayder bo‘yicha dolzarb javob haqiqiy hujjatlar qayta ishlanishidan oldin Trust Centerda e’lon qilinishi kerak." },
      { question: "Ma’lumotlarni o‘chirish mumkinmi?", answer: "Foydalanuvchi ilovadagi tasdiqlangan kanal orqali so‘rov boshlashi mumkin. O‘chirish hajmi va muddati ma’lumot turi, akkaunt holati va majburiy saqlash talablariga bog‘liq; bu shartlar bajarishdan oldin ko‘rsatilishi kerak." },
      { question: "Jonli yuristni qanday ulash mumkin?", answer: "Siz uzatiladigan savol, hujjat, reja va fayllarni tanlaysiz. Yuborishdan oldin JURO materiallar tarkibi va mavjud tijorat shartlarini ko‘rsatadi; topshirish faqat foydalanuvchi roziligidan keyin bajariladi." },
      { question: "Xizmat qancha turadi?", answer: "Bepul boshlanish 0 so‘m deb ko‘rsatilgan. Tasdiqlanmagan boshqa narxlar «Tez orada» yoki «Bog‘lanish» deb halol belgilanadi. Jonli yurist va qo‘shimcha xizmatlar narxi tasdiqlashdan oldin alohida ko‘rsatilishi kerak." },
      { question: "JURO biznes uchun mosmi?", answer: "Ha. Biznes uchun shartnomalarni tahlil qilish va yaratish, versiyalarni solishtirish, rejalar, rollar, hamkorlik, o‘zgarishlar tarixi va tayyor kontekstni mutaxassisga topshirish ko‘zda tutilgan. Aniq limitlar tasdiqlangan tarifga bog‘liq." },
      { question: "AI javobga ishonchi komil bo‘lmasa nima qilish kerak?", answer: "Xulosani avtomatik qo‘llamaslik kerak. Faktlarni aniqlashtiring, manbani ochib tekshiring, yetishmayotgan ma’lumotni belgilang va katta xavf bo‘lsa savolni jonli yuristga topshiring. Noaniqlik foydalanuvchiga ko‘rinishi kerak." },
    ],
  },
  final: {
    title: "Yuridik savol shunchaki savol bo‘lib qolmasligi kerak",
    body: "Vaziyatni tasvirlashdan boshlang — JURO manbalar, harakatlar rejasi va tayyor hujjatga o‘tishga yordam beradi.",
    primary: "Vaziyatni bepul tahlil qilish",
    secondary: "JUROga kirish",
    disclaimer: "JURO davlat organi yoki notarius emas. AI vositalari majburiy professional yordamni almashtirmaydi.",
  },
  footer: {
    description: "Yuridik savollar, hujjatlar va hamkorlik uchun himoyalangan ish makoni.",
    product: "Mahsulot", companies: "Kompaniyalar uchun", legal: "Huquqiy ma’lumot", contacts: "Aloqa",
    links: {
      ai: "AI-yurist", create: "Hujjat yaratish", review: "Hujjatni tekshirish", plan: "Harakatlar rejasi",
      business: "Biznes makoni", security: "Xavfsizlik", pricing: "Tariflar", consultations: "Maslahatlar",
      terms: "Foydalanish shartlari", privacy: "Maxfiylik siyosati", data: "Shaxsiy ma’lumotlarni qayta ishlash", cookies: "Cookies", aiRules: "AIdan foydalanish qoidalari", complaint: "Murojaat yoki shikoyat",
    },
  },
};
