import {database} from '../storage/connection';
export async function analyticsFunnels(start:string,end:string,url:URL){
 const query=async(sql:string,values:unknown[]=[]) =>(await database().pool.query(sql,values)).rows;
 const windowDays=Math.max(1,Math.min(90,Number(url.searchParams.get('window'))||30));
 const filters=['application','source','device','account_type','plan_code'].map(k=>(url.searchParams.get(k)??'').slice(0,80));
 const [funnel,cohorts,professionals,first]=await Promise.all([
 query(`WITH visits AS(SELECT application,visitor_id,min(created_at) AS visited FROM control_product_events WHERE event='page_view' AND created_at >= $1::timestamptz AND created_at < $2::timestamptz AND ($4='' OR application=$4) AND ($5='' OR source=$5) AND ($6='' OR device=$6) AND ($7='' OR account_type=$7) AND ($8='' OR plan_code=$8) GROUP BY application,visitor_id), steps AS(
 SELECT v.*,s.started,r.registered,r.user_id,a.use_at,b.repeat_at,p.paid FROM visits v
 LEFT JOIN LATERAL(SELECT min(created_at) AS started FROM control_product_events WHERE application=v.application AND visitor_id=v.visitor_id AND event='registration_started' AND created_at>=v.visited AND created_at<v.visited+$3*interval '1 day') s ON true
 LEFT JOIN LATERAL(SELECT created_at AS registered,user_id FROM control_product_events WHERE application=v.application AND visitor_id=v.visitor_id AND event='registration_completed' AND created_at>=s.started AND created_at<v.visited+$3*interval '1 day' ORDER BY created_at LIMIT 1) r ON true
 LEFT JOIN LATERAL(SELECT min(created_at) AS use_at FROM control_product_events WHERE user_id=r.user_id AND event='feature_completed' AND created_at>=r.registered AND created_at<v.visited+$3*interval '1 day') a ON true
 LEFT JOIN LATERAL(SELECT min(created_at) AS repeat_at FROM control_product_events WHERE user_id=r.user_id AND event='feature_completed' AND created_at>a.use_at+interval '1 day' AND created_at<v.visited+$3*interval '1 day') b ON true
 LEFT JOIN LATERAL(SELECT min(p.updated_at::timestamptz) AS paid FROM payments p JOIN user_profiles u ON u.default_workspace_id=p.workspace_id WHERE u.id=r.user_id AND p.status IN ('settled','succeeded','paid','confirmed') AND p.updated_at::timestamptz>=b.repeat_at AND p.updated_at::timestamptz<v.visited+$3*interval '1 day' AND NOT EXISTS(SELECT 1 FROM payment_attempts x WHERE x.payment_id=p.id AND x.provider IN ('sandbox','demo'))) p ON true
 ) SELECT application,count(*) AS visits,count(started) AS registration_started,count(registered) AS registered,count(use_at) AS first_use,count(repeat_at) AS repeated,count(paid) AS paid,count(*) FILTER(WHERE visited+($3*interval '1 day')>now()) AS immature FROM steps GROUP BY application`,[start,end,windowDays,...filters]),
 query(`WITH registrations AS(SELECT user_id,min(created_at) AS registered FROM control_product_events WHERE event='registration_completed' AND created_at >= $1::timestamptz AND created_at < $2::timestamptz AND ($3='' OR application=$3) AND ($4='' OR source=$4) AND ($5='' OR device=$5) AND ($6='' OR account_type=$6) AND ($7='' OR plan_code=$7) GROUP BY user_id)
 SELECT to_char(registered AT TIME ZONE 'Asia/Tashkent','YYYY-MM') AS cohort,count(*) AS registrations,
 count(*) FILTER(WHERE registered<now()-interval '14 days') AS mature_week_two,
 count(*) FILTER(WHERE registered<now()-interval '14 days' AND EXISTS(SELECT 1 FROM control_product_events e WHERE e.user_id=r.user_id AND e.event='feature_completed' AND e.created_at>=r.registered+interval '7 days' AND e.created_at<r.registered+interval '14 days')) AS retained_week_two,
 count(*) FILTER(WHERE registered<now()-interval '35 days') AS mature_week_five,
 count(*) FILTER(WHERE registered<now()-interval '35 days' AND EXISTS(SELECT 1 FROM control_product_events e WHERE e.user_id=r.user_id AND e.event='feature_completed' AND e.created_at>=r.registered+interval '28 days' AND e.created_at<r.registered+interval '35 days')) AS retained_week_five FROM registrations r GROUP BY 1 ORDER BY 1`,[start,end,...filters]),
 query(`WITH submissions AS(SELECT profile_id,revision,created_at AS submitted FROM control_professional_flow_events WHERE event='submitted' AND created_at >= $1::timestamptz AND created_at < $2::timestamptz), steps AS(SELECT s.*,r.reviewed,a.approved,p.published,c.consultation FROM submissions s
 LEFT JOIN LATERAL(SELECT min(created_at) AS reviewed FROM control_professional_flow_events WHERE profile_id=s.profile_id AND revision=s.revision AND event='reviewed' AND created_at>=s.submitted) r ON true
 LEFT JOIN LATERAL(SELECT min(created_at) AS approved FROM control_professional_flow_events WHERE profile_id=s.profile_id AND revision=s.revision AND event='approved' AND created_at>=r.reviewed) a ON true
 LEFT JOIN LATERAL(SELECT min(created_at) AS published FROM control_professional_flow_events WHERE profile_id=s.profile_id AND revision=s.revision AND event='published' AND created_at>=a.approved) p ON true
 LEFT JOIN LATERAL(SELECT min(created_at::timestamptz) AS consultation FROM lawyer_requests WHERE lawyer_profile_id=s.profile_id AND created_at::timestamptz>=p.published) c ON true)
 SELECT count(*) AS submitted,count(reviewed) FILTER(WHERE reviewed<submitted+$3*interval '1 day') AS reviewed,count(approved) FILTER(WHERE approved<submitted+$3*interval '1 day') AS approved,count(published) FILTER(WHERE published<submitted+$3*interval '1 day') AS published,count(consultation) FILTER(WHERE consultation<submitted+$3*interval '1 day') AS first_consultation FROM steps`,[start,end,windowDays]),
 query("SELECT min(created_at) AS collected FROM control_product_events")]);
 return {funnel,cohorts:cohorts.map(c=>({...c,retention_week_two:Number(c.mature_week_two)>0?Math.round(Number(c.retained_week_two)/Number(c.mature_week_two)*10000)/100+"%":null,retention_week_five:Number(c.mature_week_five)>0?Math.round(Number(c.retained_week_five)/Number(c.mature_week_five)*10000)/100+"%":null})),professionals,collectionStartedAt:first[0]?.collected??null,windowDays,definitions:{funnel:`Последовательная воронка: посещение → отправка регистрационной формы → подтверждённая регистрация → успешное действие → повторное успешное действие в другой день → оплата. Все шаги в ${windowDays} дней от посещения, могут завершиться после выбранного периода. Основа — браузеры отдельно по приложению; авторизованный ID связывает серверные действия. Междоменные анонимные посетители не объединяются.`,retention:'Когорта — месяц подтверждённой регистрации. Удержание: успешное действие на 7–13-й или 28–34-й день / только созревшие регистрации. При нулевой созревшей базе процент недоступен.',professional:'Воронка профессионалов основана на новых сохранённых событиях подачи и рассмотрения. Повторная редакция — отдельная подача; все шаги должны идти по порядку в одном окне.'}};
}
