import {database} from '../storage/connection';
export async function financialMetrics(start:string,end:string){const query=async(sql:string,values:unknown[]=[]) =>(await database().pool.query(sql,values)).rows;
 const [revenue,recurring,subscribers,changes,history,ai,ledger,payingUsers]=await Promise.all([
 query(`SELECT p.currency,sum(p.amount_minor) FILTER(WHERE p.status IN ('settled','succeeded','paid','success','confirmed')) AS gross_received_minor,sum(p.amount_minor) FILTER(WHERE p.status IN ('refunded','refund')) AS refunded_minor,count(DISTINCT p.workspace_id) FILTER(WHERE p.status IN ('settled','succeeded','paid','success','confirmed')) AS paying_workspaces FROM payments p WHERE p.created_at >= $1 AND p.created_at < $2 AND NOT EXISTS(SELECT 1 FROM payment_attempts a WHERE a.payment_id=p.id AND a.provider IN ('sandbox','demo')) GROUP BY p.currency`,[start,end]),
 query(`SELECT v.currency,sum(CASE WHEN v.billing_period IN ('year','yearly','annual') THEN v.price_minor/12.0 WHEN v.billing_period IN ('month','monthly') THEN v.price_minor END) AS mrr_minor FROM subscriptions s JOIN subscription_plan_versions v ON v.id=s.plan_version_id WHERE s.status='active' AND s.provider NOT IN ('sandbox','demo') AND s.provider_subscription_id IS NOT NULL GROUP BY v.currency`),
 query("SELECT status,plan_code,count(*) AS count,count(*) FILTER(WHERE current_period_ends_at::timestamptz BETWEEN now() AND now()+interval '7 days') AS expiring FROM subscriptions WHERE provider NOT IN ('sandbox','demo') GROUP BY status,plan_code"),
 query(`WITH baseline AS(SELECT DISTINCT ON(subscription_id) subscription_id,currency,mrr_minor,status FROM control_subscription_snapshots WHERE recorded_at<=$1::timestamptz ORDER BY subscription_id,recorded_at DESC), ending AS(SELECT DISTINCT ON(subscription_id) subscription_id,mrr_minor,status FROM control_subscription_snapshots WHERE recorded_at<$2::timestamptz ORDER BY subscription_id,recorded_at DESC) SELECT b.currency,count(*) FILTER(WHERE b.status='active') AS initial_active,count(*) FILTER(WHERE b.status='active' AND e.status<>'active') AS lost_subscribers,sum(b.mrr_minor) FILTER(WHERE b.status='active') AS initial_mrr_minor,sum(greatest(b.mrr_minor-coalesce(e.mrr_minor,0),0)) FILTER(WHERE b.status='active') AS lost_mrr_minor FROM baseline b JOIN ending e ON e.subscription_id=b.subscription_id GROUP BY b.currency`,[start,end]),
 query('SELECT min(recorded_at) AS collection_started_at FROM control_subscription_snapshots'),
 query('SELECT sum(estimated_cost_microusd) AS estimated_cost_microusd FROM ai_runs WHERE created_at >= $1 AND created_at < $2',[start,end]),
 query("SELECT e.currency,a.code,sum(CASE WHEN e.side='DEBIT' THEN e.amount_minor ELSE -e.amount_minor END) AS debit_net_minor,count(*) AS entries FROM ledger_entries e JOIN ledger_accounts a ON a.id=e.account_id JOIN ledger_transactions t ON t.id=e.transaction_id LEFT JOIN marketplace_orders o ON o.id=t.order_id WHERE t.status='posted' AND t.occurred_at >= $1 AND t.occurred_at < $2 AND coalesce(o.provider,'') NOT IN ('sandbox','demo') AND NOT EXISTS(SELECT 1 FROM payment_attempts x WHERE x.payment_id=t.payment_id AND x.provider IN ('sandbox','demo')) AND a.code IN ('JURO_REVENUE','SUBSCRIPTION_REVENUE','UZUM_COMMISSION_EXPENSE','REFUND_LIABILITY') GROUP BY e.currency,a.code",[start,end]),
 query("SELECT p.currency,count(DISTINCT o.customer_user_id) AS users FROM payments p JOIN payment_attempts a ON a.payment_id=p.id JOIN marketplace_orders o ON o.id=a.order_id WHERE p.created_at >= $1 AND p.created_at < $2 AND p.status IN ('settled','succeeded','paid','confirmed') AND a.provider NOT IN ('sandbox','demo') GROUP BY p.currency",[start,end])]);
 const audience=(await query("SELECT count(*) AS count FROM user_profiles u WHERE created_at<$1 AND lifecycle_status='active' AND NOT EXISTS(SELECT 1 FROM auth_pending_registrations p WHERE p.user_id=u.id)",[end]))[0];
 const currencies=[...new Set([...revenue,...recurring].map(r=>r.currency))];const metrics=currencies.map(currency=>{const r=revenue.find(v=>v.currency===currency),m=recurring.find(v=>v.currency===currency),c=changes.find(v=>v.currency===currency);const gross=r?.gross_received_minor==null?null:Number(r.gross_received_minor),refund=r?.refunded_minor==null?0:Number(r.refunded_minor),payers=Number(payingUsers.find(v=>v.currency===currency)?.users??0),population=Number(audience.count);return {currency,gross_received_minor:gross,refunded_minor:refund,net_after_recorded_refunds_minor:gross==null?null:gross-refund,mrr_minor:m?.mrr_minor??null,arr_minor:m?.mrr_minor==null?null:Number(m.mrr_minor)*12,arpu_minor:gross==null||population===0?null:(gross-refund)/population,arppu_minor:gross==null||payers===0?null:(gross-refund)/payers,paying_workspaces:Number(r?.paying_workspaces??0),paying_users:payers,provider_fees_minor:ledger.find(v=>v.currency===currency&&v.code==='UZUM_COMMISSION_EXPENSE')?.debit_net_minor??null,recognized_revenue_minor:ledger.some(v=>v.currency===currency&&['JURO_REVENUE','SUBSCRIPTION_REVENUE'].includes(v.code))?-ledger.filter(v=>v.currency===currency&&['JURO_REVENUE','SUBSCRIPTION_REVENUE'].includes(v.code)).reduce((a,b)=>a+Number(b.debit_net_minor),0):null,payment_conversion:population?payers/population:null,subscriber_churn:c&&Number(c.initial_active)>0?Number(c.lost_subscribers)/Number(c.initial_active):null,revenue_churn:c&&Number(c.initial_mrr_minor)>0?Number(c.lost_mrr_minor)/Number(c.initial_mrr_minor):null};});
 const transitions=await query(`SELECT subscription_id,plan_code,status,recorded_at FROM control_subscription_snapshots WHERE recorded_at >= $1::timestamptz AND recorded_at < $2::timestamptz ORDER BY recorded_at DESC LIMIT 50`,[start,end]);
 return {metrics,ledger,subscribers,transitions,historyStartedAt:history[0]?.collection_started_at??null,ai:ai[0],definitions:{arpu:'ARPU = поступления после зарегистрированных возвратов / число завершивших регистрацию активных пользователей на конец периода.',arppu:'ARPPU = поступления после зарегистрированных возвратов / уникальные плательщики customer_user_id подтверждённых серверных заказов за период.',conversion:'Конверсия = уникальные плательщики подтверждённых заказов / завершившие регистрацию пользователи на конец периода. Это доля за период, а не событийная воронка.',churn:'Отток подписчиков = потерянные активные подписки / активные на начало. Отток MRR = уменьшение месячной выручки исходной когорты / MRR на начало. До начала истории значение недоступно.',refunds:'Возвраты учитываются только по сохранённому статусу возврата. Признанная выручка и комиссия берутся отдельно из проведённых записей ledger. REFUND_LIABILITY — обязательство возврата, не факт выплаты; частичный возврат без подтверждённой операции не считается поступлением или списанием. Не чистая прибыль.'}};
}
