import {z} from 'zod';
import {createHash} from 'node:crypto';
import {database} from '../storage/connection';
import {getSelfHostedRuntime} from '../runtime/self-hosted';
import {malwareScannerResponseSchema} from '../document-analysis/malware-scanner';
const detailsSchema=z.object({professionalType:z.enum(['lawyer','advocate','firm','other']),organizationName:z.string().trim().max(300).nullable(),registrationNumber:z.string().trim().max(100).nullable(),licenseNumber:z.string().trim().max(100).nullable(),representatives:z.array(z.object({name:z.string().trim().min(1).max(200),position:z.string().max(200),email:z.string().email().or(z.literal(''))})).max(30)}).strict().superRefine((v,c)=>{if(v.professionalType==='advocate'&&!v.licenseNumber)c.addIssue({code:'custom',message:'Укажите сведения о лицензии адвоката',path:['licenseNumber']});if(v.professionalType==='firm'&&(!v.organizationName||!v.registrationNumber))c.addIssue({code:'custom',message:'Укажите название и регистрацию организации',path:['organizationName']});});
export async function professionalDetails(profileId:string){const db=database().pool;return {details:(await db.query('SELECT * FROM control_professional_details WHERE profile_id=$1',[profileId])).rows[0]??null,documents:(await db.query('SELECT id,kind,file_name,mime,size_bytes,revision,created_at FROM control_professional_documents WHERE profile_id=$1 ORDER BY created_at DESC',[profileId])).rows};}
export async function saveProfessionalDetails(profileId:string,userId:string,data:unknown){
 const value=detailsSchema.parse(data),client=await database().pool.connect();try{await client.query('BEGIN');const row=(await client.query('SELECT profile_revision,marketplace_status FROM lawyer_profiles WHERE id=$1 AND user_id=$2 FOR UPDATE',[profileId,userId])).rows[0];if(!row)throw Error('PROFILE_UNAVAILABLE');if(['blocked','suspended','archived'].includes(row.marketplace_status))throw Error('PROFILE_RESTRICTED');
 await client.query(`INSERT INTO control_professional_details(profile_id,professional_type,organization_name,registration_number,license_number,representatives,revision) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(profile_id) DO UPDATE SET professional_type=excluded.professional_type,organization_name=excluded.organization_name,registration_number=excluded.registration_number,license_number=excluded.license_number,representatives=excluded.representatives,revision=excluded.revision,updated_at=now()`,[profileId,value.professionalType,value.organizationName,value.registrationNumber,value.licenseNumber,JSON.stringify(value.representatives),Number(row.profile_revision)+1]);
 await client.query("UPDATE lawyer_profiles SET status='pending',marketplace_status=CASE WHEN marketplace_status='profile_incomplete' THEN 'profile_incomplete' ELSE 'pending_review' END,profile_revision=profile_revision+1,public_approved_at=NULL,firm_name=CASE WHEN $3='firm' THEN $4 ELSE firm_name END,advocate_status=CASE WHEN $3='advocate' THEN 'declared' ELSE 'not_declared' END,updated_at=$2 WHERE id=$1",[profileId,new Date().toISOString(),value.professionalType,value.organizationName]);await client.query('COMMIT');return {ok:true};
 }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}
export async function uploadProfessionalDocument(profileId:string,userId:string,file:File,kind:string){
 z.enum(['education','license','registration','authority','other']).parse(kind);if(file.size>10*1024*1024||file.size<8)throw Error('INVALID_FILE_SIZE');
 const bytes=new Uint8Array(await file.arrayBuffer());const mime=Buffer.from(bytes.slice(0,5)).toString()==='%PDF-'?'application/pdf':bytes[0]===0xff&&bytes[1]===0xd8?'image/jpeg':Buffer.from(bytes.slice(0,8)).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':null;if(!mime)throw Error('INVALID_FILE_TYPE');
 const runtime=getSelfHostedRuntime(),checksum=createHash('sha256').update(bytes).digest('hex');if(runtime.MALWARE_SCAN_ENABLED!=='true'||!runtime.MALWARE_SCANNER)throw Error('SCANNER_UNAVAILABLE');
 const scan=await runtime.MALWARE_SCANNER.fetch('https://malware-scanner.internal/v1/scan',{method:'POST',headers:{'content-type':mime,'content-length':String(file.size),'x-juro-scan-schema':'1','x-content-sha256':checksum},body:bytes});if(!scan.ok)throw Error('SCANNER_UNAVAILABLE');const verdict=malwareScannerResponseSchema.parse(await scan.json());if(verdict.verdict!=='clean'||verdict.sourceSha256!==checksum)throw Error('FILE_NOT_CLEAN');
 const id=crypto.randomUUID(),key=`professional-credentials/${profileId}/${id}`;if(!runtime.BUCKET)throw Error('STORAGE_UNAVAILABLE');
 const client=await database().pool.connect();try{await client.query('BEGIN');const row=(await client.query('SELECT profile_revision,marketplace_status FROM lawyer_profiles WHERE id=$1 AND user_id=$2 FOR UPDATE',[profileId,userId])).rows[0];if(!row||['blocked','suspended','archived'].includes(row.marketplace_status))throw Error('PROFILE_RESTRICTED');await runtime.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime},customMetadata:{purpose:'professional-verification',owner:userId}});
 await client.query('INSERT INTO control_professional_documents(id,profile_id,revision,kind,file_name,object_key,mime,size_bytes) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,profileId,Number(row.profile_revision)+1,kind,file.name.replace(/[\r\n"\\/]/g,'_').slice(0,200),key,mime,file.size]);await client.query("UPDATE lawyer_profiles SET status='pending',marketplace_status=CASE WHEN marketplace_status='profile_incomplete' THEN 'profile_incomplete' ELSE 'pending_review' END,profile_revision=profile_revision+1,public_approved_at=NULL,updated_at=$2 WHERE id=$1",[profileId,new Date().toISOString()]);await client.query('COMMIT');return {ok:true,id};
 }catch(e){await client.query('ROLLBACK');await runtime.BUCKET.delete(key).catch(()=>{});throw e;}finally{client.release();}
}
export async function professionalDocument(id:string){const row=(await database().pool.query('SELECT * FROM control_professional_documents WHERE id=$1',[id])).rows[0];if(!row)return new Response(null,{status:404});const object=await getSelfHostedRuntime().BUCKET!.get(row.object_key);if(!object)return new Response(null,{status:404});return new Response(object.body,{headers:{'content-type':row.mime,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(row.file_name)}`,'cache-control':'private, no-store','x-content-type-options':'nosniff','content-security-policy':"sandbox; default-src 'none'"}});}
